@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsInVzZXIiOiJjbGllbnRlM0BtYWlsLmNvbSIsInJvbGUiOiJjbGllbnRlIiwiaWF0IjoxNzQ5MTUzNTk2LCJleHAiOjE3NDkxNTcxOTZ9.pL7oaCMMpomz3YA404YLKh9V3sKmo3-YBNHWWkowXk0
@base_url=http://localhost:3000

### Criar uma avaliação
POST {{base_url}}/reviews
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "orderId": 1,
  "rating": 5,
  "comment": "Ótimo produto, chegou muito bem embalado!"
}

### Listar avaliações do usuário authenticado
GET {{base_url}}/reviews
Authorization: Bearer {{token}}

### Atulizar uma avaliação
PATCH {{base_url}}/reviews/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "rating": 4,
  "comment": "Produto bom, mas poderia ser melhor."
}

### Deletar uma avaliação
DELETE {{base_url}}/reviews/1
Authorization: Bearer {{token}}